import React, { createContext, useState, useEffect, useContext } from 'react';
import * as SecureStore from 'expo-secure-store';

const LanguageContext = createContext({});

// SHARED KEYS — reused across multiple screens / sections
const SHARED = {
  en: {
    // General UI
    cancel: 'Cancel',
    close: 'Close',
    done: 'Done',
    ok: 'OK',
    save: 'Save',
    saving: 'Saving…',
    updating: 'Updating…',
    creating: 'Creating...',
    loading: 'Loading...',
    uploading: 'Uploading...',
    verifying: 'Verifying...',
    sending: 'Sending...',
    deleting: 'Deleting...',
    assigning: 'Assigning…',
    generating: 'Generating...',
    select: 'Select...',
    all: 'All',
    results: 'results',

    // Common labels
    location: 'Location:',
    brand: 'Brand:',
    model: 'Model',
    station: 'Station',
    area: 'Area',
    location: 'Location',
    installedOn: 'Installed On',
    reportedOn: 'Reported On',
    reportedBy: 'Reported By',
    complaintNo: 'Complaint No',
    resolvedBy: 'Resolved By',
    resolvedOn: 'Resolved On',
    verifiedOn: 'Verified On',
    issueDescription: 'Issue Description',
    equipment: 'Equipment',
    unknown: 'Unknown',
    na: 'N/A',
    notSet: 'Not set',
    notProvided: 'Not provided',
    ackPhoto: "Acknowledgement Photo",

    // Common fields
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    role: 'Role',
    employeeId: 'Employee ID:',
    designation: 'Designation:',
    selectDesignation: 'Select designation...',
    noDesignation: 'No Designation',

    // Designation modal (shared: Add User, User Details)
    selectDesignationTitle: 'Select Designation',
    addNewDesignation: 'Add New Designation',
    newDesignation: 'New Designation',
    designationPlaceholder: 'e.g., TECHNICIAN, SUPERVISOR...',
    willBeSavedAs: 'Will be saved as:',
    addAndSelect: 'Add & Select',

    // Photo (shared: Add User, Signup, Lodge Complaint)
    takePhoto: 'Take Photo',
    chooseFromGallery: 'Choose from Gallery',
    choosePhotoSource: 'Choose Photo Source',
    uploading: 'Uploading...',
    photoUploaded: 'Photo uploaded successfully!',
    photoUploadFailed: 'Failed to upload photo. Please try again.',
    requiredForStaff: 'Required for Staff',
    tapToAddPhoto: 'Tap to add photo',
    cameraOrGallery: 'Camera or Gallery',

    // Permissions (shared: Add User, Signup)
    permissionsRequired: 'Permissions Required',
    cameraPermissionMsg: 'Camera and photo library access is needed to upload profile pictures.',

    // Email verification (shared: Add User, Signup)
    sendVerificationCode: 'Send Verification Code',
    sending: 'Sending...',
    codeSent: 'Code Sent! 📧',
    codeSentMsg: 'A 6-digit verification code has been sent to this email address.',
    verifyCode: 'Verify Code',
    verifying: 'Verifying...',
    emailVerified: 'Email verified successfully',
    emailNotVerified: 'Email Not Verified',

    // Password strength (shared: Add User, Signup, Forgot Password, Profile)
    tooShort: 'Too short',
    addLetterNumber: 'Add letter + number',
    strong: 'Strong ✓',

    // Password match (shared: Signup, Forgot Password, Profile)
    passwordsMatch: 'Passwords match',
    passwordsNotMatch: 'Passwords do not match',
    passwordMismatch: 'Passwords do not match',

    // Common password errors
    passwordMin: 'Password must be at least 6 characters',
    weakPassword: 'Weak Password',
    passwordRules: 'Password must contain at least one letter and one number',

    // Common email errors
    error: 'Error',
    success: 'Success',
    invalidEmail: 'Invalid Email',
    enterEmail: 'Please enter your email',
    enterValidEmail: 'Please enter a valid email address',

    // Common complaint labels (shared: All Complaints, My Complaints, Complaint Details, Job Details)
    assignedTo: 'Assigned To:',
    notAssigned: 'Not assigned yet',
    handledBy: 'Handled by:',
    open: 'Open',
    assigned: 'Assigned',
    inProgress: 'In Progress',
    closed: 'Closed',
    filterByStatus: 'Filter by Status',
    allComplaints: 'All Complaints',
    searchComplaints: 'Search by Asset ID or description',
    tapToView: 'Tap to view',
    noComplaintsYet: 'No Complaints Yet',

    // Image viewer (shared: Complaint Details, Job Details, My Complaints)
    tapToEnlarge: 'Tap to enlarge',
    tapToClose: 'Tap anywhere to close',

    // Staff leave (shared: Complaint Details, Manage Users, Staff Dashboard)
    onLeave: 'On Leave',
    staffOnLeave: 'Staff On Leave',
    markAvailable: 'Mark Available',
    markOnLeave: 'Mark On Leave',

    // Save / update actions
    saveChanges: 'Save Changes',
    updateFailed: 'Failed to update',

    // Delete actions
    deleteForever: 'Delete Forever',
    deleting: 'Deleting...',

    // Common user fields
    noName: 'No Name',
    enterFullName: 'Please enter full name',

    // OTP (shared: Job Details, My Complaints, Verify OTP)
    verifying: 'Verifying...',
    invalidOtp: 'Invalid OTP',
    complaintClosed: 'Complaint has been closed successfully',

    // Buttons shared
    login: 'Log In',
    signUp: 'Sign Up',
    user: 'User',
    staff: 'Staff',
    admin: 'Admin',
    welcome: 'Welcome',
    reportAnalysis: 'Report & Analysis',

    // Phone
    digitsCount: 'digits',

    // Date
    selectDate: 'Select Date',
    done: 'Done',
  },

  hi: {
    // General UI
    cancel: 'रद्द करें',
    close: 'बंद करें',
    done: 'पूर्ण',
    ok: 'ठीक है',
    save: 'सहेजें',
    saving: 'सहेजा जा रहा है…',
    updating: 'अपडेट हो रहा है…',
    creating: 'बनाया जा रहा है...',
    loading: 'लोड हो रहा है...',
    uploading: 'अपलोड हो रहा है...',
    verifying: 'सत्यापित किया जा रहा है...',
    sending: 'भेजा जा रहा है...',
    deleting: 'हटाया जा रहा है...',
    assigning: 'असाइन किया जा रहा है…',
    generating: 'बनाया जा रहा है...',
    select: 'चुनें...',
    all: 'सभी',
    results: 'परिणाम',

    // Common labels
    location: 'स्थान:',
    brand: 'ब्रांड:',
    model: 'मॉडल',
    station: 'स्टेशन',
    area: 'क्षेत्र',
    location: 'स्थान',
    installedOn: 'स्थापित तिथि',
    reportedOn: 'रिपोर्ट की तिथि',
    reportedBy: 'रिपोर्ट किया गया',
    complaintNo: 'शिकायत संख्या',
    resolvedBy: 'समाधान किया',
    resolvedOn: 'समाधान की तिथि',
    verifiedOn: 'सत्यापित तिथि:',
    issueDescription: 'समस्या विवरण',
    equipment: 'उपकरण',
    unknown: 'अज्ञात',
    na: 'उपलब्ध नहीं',
    notSet: 'सेट नहीं',
    notProvided: 'उपलब्ध नहीं',
    ackPhoto: 'स्वीकृति फोटो',

    // Common fields
    fullName: 'पूरा नाम',
    email: 'ईमेल',
    phone: 'फोन',
    role: 'भूमिका',
    employeeId: 'कर्मचारी आईडी:',
    designation: 'पद:',
    selectDesignation: 'पद चुनें...',
    noDesignation: 'कोई पद नहीं',

    // Designation modal
    selectDesignationTitle: 'पद चुनें',
    addNewDesignation: 'नया पद जोड़ें',
    newDesignation: 'नया पद',
    designationPlaceholder: 'जैसे: TECHNICIAN, SUPERVISOR...',
    willBeSavedAs: 'इस रूप में सेव होगा:',
    addAndSelect: 'जोड़ें और चुनें',

    // Photo
    takePhoto: 'फोटो लें',
    chooseFromGallery: 'गैलरी से चुनें',
    choosePhotoSource: 'फोटो स्रोत चुनें',
    uploading: 'अपलोड हो रहा है...',
    photoUploaded: 'फोटो सफलतापूर्वक अपलोड हुई!',
    photoUploadFailed: 'फोटो अपलोड करने में विफल। कृपया पुनः प्रयास करें।',
    requiredForStaff: 'स्टाफ के लिए आवश्यक',
    tapToAddPhoto: 'फोटो जोड़ने के लिए टैप करें',
    cameraOrGallery: 'कैमरा या गैलरी',

    // Permissions
    permissionsRequired: 'अनुमति आवश्यक',
    cameraPermissionMsg: 'प्रोफाइल फोटो अपलोड करने के लिए कैमरा और गैलरी की अनुमति आवश्यक है।',

    // Email verification
    sendVerificationCode: 'वेरिफिकेशन कोड भेजें',
    sending: 'भेजा जा रहा है...',
    codeSent: 'कोड भेजा गया! 📧',
    codeSentMsg: 'इस ईमेल पर 6 अंकों का वेरिफिकेशन कोड भेजा गया है।',
    verifyCode: 'कोड सत्यापित करें',
    verifying: 'सत्यापन हो रहा है...',
    emailVerified: 'ईमेल सफलतापूर्वक सत्यापित हुआ',
    emailNotVerified: 'ईमेल सत्यापित नहीं है',

    // Password strength
    tooShort: 'बहुत छोटा',
    addLetterNumber: 'अक्षर और संख्या जोड़ें',
    strong: 'मजबूत ✓',

    // Password match
    passwordsMatch: 'पासवर्ड मेल खाते हैं',
    passwordsNotMatch: 'पासवर्ड मेल नहीं खाते',
    passwordMismatch: 'पासवर्ड मेल नहीं खाते',

    // Common password errors
    passwordMin: 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
    weakPassword: 'कमज़ोर पासवर्ड',
    passwordRules: 'पासवर्ड में कम से कम एक अक्षर और एक संख्या होनी चाहिए',

    // Common email errors
    error: 'त्रुटि',
    success: 'सफलता',
    invalidEmail: 'अमान्य ईमेल',
    enterEmail: 'कृपया अपना ईमेल दर्ज करें',
    enterValidEmail: 'कृपया सही ईमेल दर्ज करें',

    // Common complaint labels
    assignedTo: 'असाइन किया गया:',
    notAssigned: 'अभी असाइन नहीं किया गया',
    handledBy: 'संबंधित व्यक्ति:',
    open: 'खुली',
    assigned: 'असाइन की गई',
    inProgress: 'प्रगति में',
    closed: 'बंद',
    filterByStatus: 'स्थिति के अनुसार फ़िल्टर करें',
    allComplaints: 'सभी शिकायतें',
    searchComplaints: 'एसेट आईडी या विवरण से खोजें',
    tapToView: 'देखने के लिए टैप करें',
    noComplaintsYet: 'अभी कोई शिकायत नहीं',

    // Image viewer
    tapToEnlarge: 'बड़ा देखने के लिए टैप करें',
    tapToClose: 'बंद करने के लिए कहीं भी टैप करें',

    // Staff leave
    onLeave: 'अवकाश पर',
    staffOnLeave: 'स्टाफ अवकाश पर',
    markAvailable: 'उपलब्ध करें',
    markOnLeave: 'अवकाश पर करें',

    // Save / update
    saveChanges: 'परिवर्तन सहेजें',
    updateFailed: 'अपडेट करने में विफल',

    // Delete
    deleteForever: 'हमेशा के लिए हटाएं',
    deleting: 'हटाया जा रहा है...',

    // Common user fields
    noName: 'कोई नाम नहीं',
    enterFullName: 'कृपया पूरा नाम दर्ज करें',

    // OTP
    invalidOtp: 'अमान्य OTP',
    complaintClosed: 'शिकायत सफलतापूर्वक बंद हो गई',

    // Buttons
    login: 'लॉग इन करें',
    signUp: 'साइन अप करें',
    user: 'उपयोगकर्ता',
    staff: 'स्टाफ',
    admin: 'एडमिन',
    welcome: 'स्वागत है',
    reportAnalysis: 'Report & Analysis',

    // Phone
    digitsCount: 'अंक',

    // Date
    selectDate: 'तारीख चुनें',
  },
};

// SCREEN-SPECIFIC TRANSLATIONS
const SCREEN_TRANSLATIONS = {
  en: {
    // ── ADMIN 

    // 1. Add Asset Screen
    addEquipment: 'Add Equipment',
    equipmentType: 'Equipment Type',
    selectEquipmentType: 'Select equipment type...',
    selectedType: 'Selected Type',
    equipmentDetails: 'Equipment Details',
    assetId: 'Asset ID',
    assetIdPlaceholder: 'e.g., AC-3F-001',
    locationPlaceholder: 'e.g., 3rd Floor, Room 301',
    brand: 'Brand',
    brandPlaceholder: 'e.g., Voltas, Daikin',
    model: 'Model',
    modelPlaceholder: 'e.g., 183V ADP',
    installDate: 'Install Date',
    selectInstallDate: 'Select install date',
    createEquipment: 'Create Equipment',
    assetidalert: 'Please enter Asset ID',
    locationalert: 'Please enter location',
    installdatealert: 'Please select install date',
    createalert: 'Success',
    hasbeenadded: 'has been added successfully',
    viewAsset: 'View Asset',
    failedToCreate: 'Failed to create asset',
    selectEquipmentTypeTitle: 'Select Equipment Type',
    noTypes: 'No types yet. Add one below.',
    addNewType: 'Add New Type',
    newTypeName: 'New Type Name',
    customTypePlaceholder: 'e.g., FAN, PROJECTOR, UPS...',
    enterTypeName: 'Please enter a type name',
    typeMinLength: 'Type name must be at least 2 characters',
    alreadyExists: 'This type already exists. Selecting it.',

    // 2. Add User Screen
    addUser: 'Add User',
    selectRole: 'Select Role',
    photo: 'Photo',
    useCamera: 'Use camera to take a new photo',
    selectFromLibrary: 'Select from your photo library',
    basicInformation: 'Basic Information',
    fullNameLabel: 'Full Name *',
    emailLabel: 'Email *',
    password: 'Password * (min 6 chars)',
    phoneNumber: 'Phone Number * (10 digits)',
    emailVerificationRequired: 'Email Verification Required',
    enterCode: '6-digit code',
    emailAlreadyExists: 'This email is already registered in the system.',
    invalidPhoneStart: 'Must start with 6, 7, 8, or 9',
    staffDetails: 'Staff Details',
    employeeIdInput: 'Employee ID * (e.g., EMP001)',
    designationLabel: 'Designation',
    createUser: 'Create User',
    createStaff: 'Create Staff Member',
    createAdmin: 'Create Admin',
    userCreated: 'User Created!',
    failedToCreateUser: 'Failed to create user',
    enterVerificationCode: 'Please enter the 6-digit verification code',
    enterPhone: 'Please enter phone number',
    phoneMustBe10: 'Phone number must be exactly 10 digits',
    employeeIdRequired: 'Employee ID is required for staff',
    photoRequired: 'Please upload a photo for the staff member',
    enterDesignation: 'Please enter a designation',
    designationMin: 'Designation must be at least 2 characters',

    // 3. Admin Dashboard
    trackManage: 'Track and manage your system efficiently',
    totalComplaints: 'Total Complaints',
    openComplaints: 'Open Complaints',
    assignedComplaints: 'Assigned Complaints',
    inProgressComplaints: 'In Progress',
    closedComplaints: 'Closed Complaints',
    staffOnDuty: 'Staff On Duty',
    staffUnavailable: 'Staff Unavailable',
    totalAssets: 'Total Assets',
    quickActions: 'Quick Actions',
    recentComplaints: 'Recent Complaints',
    viewAllComplaints: 'View All \n Complaints',
    needAssignment: 'need \n assignment',
    complaintAnalysis: 'Complaint \n Analysis',
    noComplaints: 'No complaints found',
    verifyOtp: 'Verify OTP',

    // 4. All Assets Screen
    equipments: 'Equipments',
    searchPlaceholder: 'Search by ID, location or brand...',
    filterByType: 'Filter by Type',
    allEquipment: 'All Equipment',
    airConditioners: 'Air Conditioners',
    waterCoolers: 'Water Coolers',
    desertCoolers: 'Desert Coolers',
    inactive: 'Inactive',
    active: 'Active',
    inactiveStatus: 'Inactive',
    equipmentCount: 'equipment',
    noEquipmentFound: 'No Equipment Found',
    noInactiveEquipment: 'No Inactive Equipment',
    noEquipmentType: 'No equipment of this type',
    equipmentWillAppear: 'Equipment will appear here',
    allActiveMessage: 'All equipment is currently active',
    noEquipmentTypeFound: 'No equipment of this type found',

    // 5. All Complaints Screen
    complaints: 'Complaints',
    staffOnLeaveTag: 'Staff on Leave',
    totalComplaintsCount: 'Total complaints',
    noStaffOnLeave: 'No Staff On Leave',
    noComplaintsType: 'No complaints',
    complaintsWillAppear: 'Complaints will appear here',
    noStaffLeaveComplaints: 'No complaints have staff on leave',
    complaintsStatusAppear: 'Complaints with this status will appear here',

    // 6. Asset Details Screen
    equipmentId: 'Equipment ID:',
    type: 'Type:',
    locationRequired: 'Location is required',
    editLocation: 'Location *',
    editBrand: 'Brand',
    editModel: 'Model',
    installedDate: 'Installed Date',
    updateSuccess: 'Equipment details updated',
    updateFailed: 'Failed to update asset',
    activate: 'Activate',
    deactivate: 'Deactivate',
    activateEquipment: 'Activate Equipment?',
    deactivateEquipment: 'Deactivate Equipment?',
    activateMessage: 'This will mark this equipment as active again.',
    deactivateMessage: "This will mark this equipment as inactive. It won't appear in QR scans.",
    toggleFailed: 'Failed to toggle status',
    availableForComplaints: 'Available for complaints',
    hiddenFromQR: 'Hidden from QR scans',
    qrCode: 'QR Code',
    scanHint: 'Scan this QR code with Scan2Fix app to report issues',
    getQrCode: 'Get QR Code',
    qrSaved: 'QR code image generated successfully',
    qrFailed: 'Failed to generate QR image',
    selectDateTitle: 'Select Date',

    // 7. Complaint Details Screen
    complaintDetails: 'Complaint Details',
    attachedPhoto: 'Attached Photo',
    assignStaff: 'Assign Staff',
    assignedStaff: 'Assigned Staff',
    describeIssue: 'Describe the issue...',
    characters: 'characters',
    minChars: '(min 10)',
    assign: 'Assign Staff',
    reassign: 'Reassign Staff',
    selectStaffError: 'Please select a staff member',
    selectedStaff:'Selected Staff',
    cannotAssign: 'Cannot Assign',
    staffOnLeaveMsg: 'is on leave.',
    descriptionEmpty: 'Description cannot be empty',
    descriptionMin: 'Description must be at least 10 characters',
    descUpdated: 'Description updated',
    descUpdateFailed: 'Failed to update description',
    selectStaff: 'Select Staff Member',
    selectStaffPlaceholder: '-- Select Staff --',
    available: '✓',
    current: 'Currently:',
    maintenanceStaff: 'Maintenance Staff',
    pendingAssignment: 'Pending Assignment',
    staffWillAssign: 'A staff member will be assigned shortly',
    staffOnLeaveWarning: 'Assigned staff is currently on leave. Consider reassigning.',
    staffCurrentlyOnLeave: 'This staff member is currently on leave',
    selectedStaffOnLeave: 'This staff member is on leave',

    // 8. Manage Users Screen
    manageUsers: 'Manage Users',
    searchUsers: 'Search by name, email or ID...',
    filterUsers: 'Filter Users',
    allUsers: 'All Users',
    admins: 'Admins',
    allStaff: 'All Staff',
    staffOnDuty: 'Staff On Duty',
    users: 'Users',
    byDesignation: 'By Designation',
    onDuty: 'On Duty',
    onLeaveStatus: 'On Leave',
    markOnLeaveTitle: 'Mark On Leave',
    markAvailableTitle: 'Mark Available',
    confirm: 'Confirm',
    markStatusMessage: 'Mark user as status?',
    userNowStatus: 'is now',
    usersCount: 'users',
    noUsersFound: 'No Users Found',
    noStaffOnDuty: 'No Staff On Duty',
    noUsersRole: 'No Users',
    tryDifferentFilter: 'Try a different filter',

    // 9. User Details Screen
    userDetails: 'User Details',
    joinedOn: 'Joined On:',
    enterPhone: 'Enter phone',
    userUpdated: 'User details updated',
    staffActions: 'Staff Actions',
    markAsAvailable: 'Mark as Available',
    markAsOnLeave: 'Mark as On Leave',
    currentlyOnLeave: 'Currently On Leave',
    dangerZone: 'Danger Zone',
    deleteUser: 'Delete User Account',
    deleteWarning: 'This will permanently delete this user and all associated data',
    deleteUserTitle: 'Delete User?',
    deleteUserConfirm: 'Are you sure you want to delete this user?',
    masterAdminProtected: 'Master Admin account is protected and cannot be deleted',
    fullNameRequired: 'Full name is required',
    userUpdateFailed: 'Failed to update user',

    // ── AUTH ──────────────────────────────────────────────────────────────────

    // 1. Forgot Password Screen
    forgotPassword: 'Forgot Password?',
    enterResetCode: 'Enter Reset Code',
    newPasswordTitle: 'New Password',
    enterEmailSubtitle: "Enter your email and we'll send a reset code",
    enterCodeSubtitle: 'Enter the 6-digit code from your admin',
    createPasswordSubtitle: 'Create a strong new password',
    emailPlaceholder: 'Email address',
    codePlaceholder: '000000',
    newPasswordPlaceholder: 'New Password',
    confirmPasswordPlaceholder: 'Confirm Password',
    sendResetCode: 'SEND RESET CODE',
    resetPassword: 'RESET PASSWORD',
    previousStep: 'Previous Step',
    backToLogin: 'Back to Login',
    codeSentForgot: 'A reset code has been generated.',
    failedToSendCode: 'Failed to send reset code',
    enterCodeError: 'Please enter the 6-digit reset code',
    passwordTooShort: 'Password must be at least 6 characters',
    passwordRequirements: 'Password must contain at least one letter and one number',
    passwordReset: 'Password Reset! ✅',
    passwordResetMsg: 'You can now login with your new password.',
    failedToReset: 'Failed to reset password',

    // 2. Login Screen
    welcomeBack: 'Welcome back!',
    loginSubtitle: 'Log in to your Scan2Fix account',
    passwordPlaceholder: 'Password',
    login: 'LOG IN',
    loggingIn: 'LOGGING IN...',
    noAccount: "Don't have an account?",
    enterPassword: 'Please enter your password',
    loginFailed: 'Login Failed',
    orSignIn: 'Or sign in using',
    enterValidEmailExample: 'Please enter a valid email address\n\nExample: user@company.com',

    // 3. Signup Screen
    createAccount: 'Create Account',
    joinScan2Fix: 'Join Scan2Fix to',
    fixIssues: 'fix issues',
    reportIssues: 'report issues',
    selectRolePrompt: 'I want to join as',
    reportIssuesDesc: 'Report issues',
    fixIssuesDesc: 'Fix issues',
    selectYourRole: 'Select Your Role',
    employeeIdSignup: 'Employee ID (e.g., EMP001)',
    phonePlaceholder: 'Phone (10 digits)',
    confirmPassword: 'Confirm Password',
    profilePhoto: 'Profile Photo',
    photoCancel: 'Cancel',
    resendIn: 'Resend in',
    enterVerificationCodePrompt: 'Enter Verification Code',
    checkEmailCode: 'Check your email for the 6-digit code',
    emailExists: 'Email Already Registered',
    goToLogin: 'Go to Login',
    invalidCode: 'Invalid Code',
    enterCode6: 'Please enter the 6-digit verification code',
    verifyEmailFirst: 'Please verify your email first',
    passwordRequired: 'Please enter a password',
    invalidPhone: 'Invalid Phone',
    phoneDigits: 'Phone number must be exactly 10 digits',
    phoneStart: 'Indian mobile numbers must start with 6, 7, 8, or 9',
    employeeIdRequiredSignup: 'Employee ID is required for staff members',
    photoRequiredTitle: 'Photo Required',
    accountCreated: 'Account Created! 🎉',
    signupFailed: 'Signup Failed',
    verificationRequired: 'Verification Required',
    signUpBtn: 'SIGN UP',
    creatingBtn: 'CREATING...',
    alreadyAccount: 'Already have an account?',
    nameMin: 'Name must be at least 2 characters',

    // ── SHARED SCREENS ────────────────────────────────────────────────────────

    // Profile Screen
    loadingProfile: 'Loading profile…',
    profileInformation: 'Profile Information',
    profileInfo: 'Profile Information',
    theme: 'Theme',
    language: 'Language',
    enterName: 'Enter your name',
    phonePlaceholderProfile: 'Enter 10-digit phone number',
    validPhone: 'Valid phone number',
    enterNameError: 'Please enter your name',
    phoneMustBe10: 'Phone number must be exactly 10 digits',
    profileUpdated: 'Profile updated successfully',
    profileUpdateFailed: 'Failed to update profile',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password (min 6, letter + number)',
    confirmNewPassword: 'Confirm New Password',
    updatePassword: 'Update Password',
    currentPasswordRequired: 'Please enter your current password',
    passwordChanged: 'Password changed successfully',
    passwordChangeFailed: 'Failed to change password',
    deleteAccount: 'Delete Account',
    deleteAccountWarning: 'This action is permanent and cannot be undone. All your data will be deleted.',
    enterPasswordToConfirm: 'Enter your password to confirm',
    deleteAccountForever: 'Delete My Account Forever',
    finalConfirmation: '⚠️ Final Confirmation',
    deleteConfirmMsg: 'Are you absolutely sure? This action cannot be undone.\n\nYour account and all associated data will be permanently deleted.',
    accountDeleted: 'Account Deleted',
    accountDeletedMsg: 'Your account has been permanently deleted.',
    deleteFailed: 'Failed to delete account',
    logout: 'Logout',
    logoutConfirm: 'Are you sure you want to logout?',
    appName: 'Scan2Fix',
    version: 'Version',

    // ── STAFF ─────────────────────────────────────────────────────────────────

    // 1. Job Details Screen
    jobDetails: 'Job Details',
    photoOfIssue: 'Photo of Issue',
    actions: 'Actions',
    startWorking: 'Start Working',
    finishWorking: 'Finish Working',
    enterOtpToComplete: 'Enter OTP to Complete',
    verifyAndClose: 'Verify & Close Job',
    statusUpdated: 'Status updated to',
    otpIncomplete: 'Please enter the complete 6-digit OTP',
    finishHint: 'Click when work is completed.',
    otpHint: 'Ask the user for the completion OTP to verify and close this job',
    otpNote: 'User generates this OTP from their app after you complete the work',
    enterCompletionOtp: 'Enter Completion OTP',
    otpSubtitle: 'Ask the user for the 6-digit OTP to verify completion',

    // 2. Staff Dashboard Screen
    goOnLeaveTitle: '🏖️ Go On Leave?',
    comeBackTitle: 'Come Back?',
    goOnLeaveMsg: 'You will NOT receive new task assignments while on leave.\n\nYour existing tasks will remain assigned to you until reassigned by Admin.',
    comeBackMsg: 'You will start receiving new task assignments again.',
    goOnLeave: 'Go On Leave',
    comeBack: 'Come Back',
    yesGoOnLeave: 'Yes, Go On Leave',
    yesAvailable: "Yes, I'm Available",
    available: 'Available',
    notReceivingTasks: 'Not receiving new tasks',
    receivingTasks: 'Receiving task assignments',
    onLeaveSuccess: '🏖️ On Leave',
    job: 'job',
    jobs: 'jobs',
    viewDetails: 'View details',
    hasPhoto: 'Has attached photo',
    noNewTasks: 'No new tasks',
    noTasksInProgress: 'No tasks in progress',
    noCompletedTasks: 'No completed tasks yet',
    newTasksHint: 'New assigned tasks will appear here',
    inProgressHint: "Tasks you're working on will appear here",
    completedHint: 'Completed tasks will appear here',

    // ── USER ──────────────────────────────────────────────────────────────────

    // 1. Lodge Complaint Screen
    lodgeComplaint: 'Lodge Complaint',
    issuePlaceholder: "What's the problem? Be as detailed as possible...",
    describeIssueLabel: 'Describe the Issue',
    attachPhoto: 'Attach Photo (Optional)',
    camera: 'Camera',
    takePhotoLabel: 'Take a photo',
    gallery: 'Gallery',
    chooseExisting: 'Choose existing',
    photoAttached: 'Photo attached',
    permissionNeeded: 'Permission Needed',
    cameraPermission: 'Camera access is required.',
    galleryPermission: 'Gallery access is required.',
    describeIssueError: 'Please describe the issue',
    complaintSubmitted: 'Complaint submitted successfully',
    submitComplaint: 'Submit Complaint',
    submitting: 'Submitting...',
    uploadingPhoto: 'Uploading photo...',

    // 2. My Complaints Screen
    myComplaints: 'My Complaints',
    finishing: 'Finishing',
    totalComplaintsLabel: 'Total complaints —',
    tapToViewImage: 'Tap to view full image',
    generateOtp: 'Generate OTP for Completion',
    shareOtp: 'Share OTP',
    completionOtp: 'Completion OTP',
    otpSubtitleUser: 'Share this OTP with the technician to verify completion',
    validFor: 'Valid for 5 minutes',
    otpNoteUser: 'Technician will enter this OTP in their app to confirm the issue is resolved',
    generateOtpFailed: 'Failed to generate OTP',
    noComplaintsDesc: 'Your submitted complaints will appear here',
    noFilteredComplaints: 'No Complaints',
    noFilteredDesc: 'Complaints with this status will appear here',
    calendar: 'calendar',

    // 3. Scan QR Screen
    requestingPermission: 'Requesting camera permission...',
    cameraAccessNeeded: 'Camera Access Needed',
    cameraPermissionDesc: 'We need camera permission to scan QR codes on machines',
    grantPermission: 'Grant Permission',
    enterManuallyLink: 'Or enter Asset ID manually',
    scanQrCode: 'Scan QR Code',
    scanInstructions: 'Point camera at QR code on the machine',
    enterIdManually: 'Enter ID Manually',
    scanAgain: 'Tap to Scan Again',
    lookingUpAsset: 'Looking up asset...',
    assetNotFound: 'Asset Not Found ❌',
    assetNotFoundMsg: 'No machine found with ID:',
    invalidQrHint: 'Make sure you are scanning a valid Scan2Fix QR code.',
    tryAgain: 'Try Again',
    enterManually: 'Enter Manually',
    scanFailed: 'Failed to process QR code. Please try again.',
    enterAssetId: 'Enter Asset ID',
    enterAssetHint: 'Enter the ID printed on the machine (e.g., AC-101, WC-201)',
    assetPlaceholder: 'e.g., AC-101',
    submit: 'Submit',
    enterAssetError: 'Please enter an Asset ID',

    // 4. User Dashboard Screen
    scanQR: 'Scan QR Code',
    reportIssue: 'Report an Issue',
    howItWorks: 'How it works:',
    step1: 'Scan the QR code on the machine',
    step2: 'Describe the issue',
    step3: 'Take a photo (optional)',
    step4: 'Submit and track status',

    // 5. Verify OTP Screen
    verifyComplaint: 'Verify Complaint',
    verifyCompletion: 'Verify Completion',
    otpInstruction: 'Enter the 6-digit OTP provided by maintenance staff',
    enterOtp: 'Enter OTP',
    otpExpired: 'OTP Expired',
    timeRemaining: 'remaining',
    verifyAndCloseComplaint: 'Verify & Close Complaint',
    invalidOtpMsg: 'Enter a valid 6-digit OTP',
    verificationFailed: 'Verification failed',
    verified: 'Verified! ✅',
    otpExpiredMsg: 'OTP has expired. Please ask staff to generate a new one.',
    otpHelpNote: 'The maintenance staff will provide you this OTP after completing the repair work. OTP is valid for 5 minutes.',
  },

  hi: {
    // ── ADMIN ─────────────────────────────────────────────────────────────────

    // 1. Add Asset Screen
    addEquipment: 'उपकरण जोड़ें',
    equipmentType: 'उपकरण का प्रकार',
    selectEquipmentType: 'उपकरण का प्रकार चुनें...',
    selectedType: 'चयनित प्रकार',
    equipmentDetails: 'उपकरण का विवरण',
    assetId: 'एसेट आईडी',
    assetIdPlaceholder: 'जैसे: AC-3F-001',
    locationPlaceholder: 'जैसे: तीसरी मंजिल, कमरा 301',
    brand: 'ब्रांड',
    brandPlaceholder: 'जैसे: Voltas, Daikin',
    model: 'मॉडल',
    modelPlaceholder: 'जैसे: 183V ADP',
    installDate: 'इंस्टॉल की तारीख ',
    selectInstallDate: 'इंस्टॉल की तारीख चुनें',
    createEquipment: 'उपकरण बनाएं',
    assetidalert: 'कृपया एसेट आईडी दर्ज करें',
    locationalert: 'कृपया स्थान दर्ज करें',
    installdatealert: 'कृपया इंस्टॉल की तारीख चुनें',
    createalert: 'सफलता',
    hasbeenadded: 'सफलतापूर्वक जोड़ा गया',
    viewAsset: 'एसेट देखें',
    failedToCreate: 'उपकरण बनाने में विफल',
    selectEquipmentTypeTitle: 'उपकरण का प्रकार चुनें',
    noTypes: 'अभी कोई प्रकार उपलब्ध नहीं है। नीचे जोड़ें।',
    addNewType: 'नया प्रकार जोड़ें',
    newTypeName: 'नए प्रकार का नाम',
    customTypePlaceholder: 'जैसे: FAN, PROJECTOR, UPS...',
    enterTypeName: 'कृपया प्रकार का नाम दर्ज करें',
    typeMinLength: 'प्रकार का नाम कम से कम 2 अक्षरों का होना चाहिए',
    alreadyExists: 'यह प्रकार पहले से मौजूद है। इसे चयनित किया जा रहा है।',

    // 2. Add User Screen
    addUser: 'उपयोगकर्ता जोड़ें',
    selectRole: 'भूमिका चुनें',
    photo: 'फोटो',
    useCamera: 'नई फोटो लेने के लिए कैमरा उपयोग करें',
    selectFromLibrary: 'अपनी गैलरी से चुनें',
    basicInformation: 'मूल जानकारी',
    fullNameLabel: 'पूरा नाम *',
    emailLabel: 'ईमेल *',
    password: 'पासवर्ड * (कम से कम 6 अक्षर)',
    phoneNumber: 'फोन नंबर * (10 अंक)',
    emailVerificationRequired: 'ईमेल सत्यापन आवश्यक',
    enterCode: '6 अंकों का कोड',
    emailAlreadyExists: 'यह ईमेल पहले से पंजीकृत है',
    invalidPhoneStart: '6, 7, 8 या 9 से शुरू होना चाहिए',
    staffDetails: 'स्टाफ विवरण',
    employeeIdInput: 'कर्मचारी आईडी * (जैसे: EMP001)',
    designationLabel: 'पद',
    createUser: 'यूज़र बनाएं',
    createStaff: 'स्टाफ सदस्य बनाएं',
    createAdmin: 'एडमिन बनाएं',
    userCreated: 'यूज़र सफलतापूर्वक बनाया गया!',
    failedToCreateUser: 'यूज़र बनाने में विफल',
    enterVerificationCode: 'कृपया 6 अंकों का कोड दर्ज करें',
    enterPhone: 'कृपया फोन नंबर दर्ज करें',
    phoneMustBe10: 'फोन नंबर 10 अंकों का होना चाहिए',
    employeeIdRequired: 'स्टाफ के लिए कर्मचारी आईडी आवश्यक है',
    photoRequired: 'स्टाफ के लिए फोटो अपलोड करें',
    enterDesignation: 'कृपया पद दर्ज करें',
    designationMin: 'पद कम से कम 2 अक्षरों का होना चाहिए',

    // 3. Admin Dashboard
    trackManage: 'अपने सिस्टम को ट्रैक और प्रबंधित करें',
    totalComplaints: 'कुल शिकायतें',
    openComplaints: 'खुली शिकायतें',
    assignedComplaints: 'असाइन की गई शिकायतें',
    inProgressComplaints: 'प्रगति में',
    closedComplaints: 'बंद शिकायतें',
    staffOnDuty: 'ड्यूटी पर स्टाफ',
    staffUnavailable: 'अनुपलब्ध स्टाफ',
    totalAssets: 'कुल उपकरण',
    quickActions: 'त्वरित कार्य',
    recentComplaints: 'हाल की शिकायतें',
    viewAllComplaints: 'सभी  \n शिकायतें देखें',
    needAssignment: 'को असाइन \n करना है',
    complaintAnalysis: 'शिकायत \n विश्लेषण',
    noComplaints: 'कोई शिकायत नहीं मिली',
    verifyOtp: 'OTP सत्यापित करें',

    // 4. All Assets Screen
    equipments: 'उपकरण',
    searchPlaceholder: 'आईडी, स्थान या ब्रांड से खोजें...',
    filterByType: 'प्रकार के अनुसार फ़िल्टर करें',
    allEquipment: 'सभी उपकरण',
    airConditioners: 'एयर कंडीशनर',
    waterCoolers: 'वॉटर कूलर',
    desertCoolers: 'डेजर्ट कूलर',
    inactive: 'निष्क्रिय',
    active: 'सक्रिय',
    inactiveStatus: 'निष्क्रिय',
    equipmentCount: 'उपकरण',
    noEquipmentFound: 'कोई उपकरण नहीं मिला',
    noInactiveEquipment: 'कोई निष्क्रिय उपकरण नहीं',
    noEquipmentType: 'इस प्रकार का कोई उपकरण नहीं',
    equipmentWillAppear: 'उपकरण यहाँ दिखाई देंगे',
    allActiveMessage: 'सभी उपकरण वर्तमान में सक्रिय हैं',
    noEquipmentTypeFound: 'इस प्रकार का कोई उपकरण नहीं मिला',

    // 5. All Complaints Screen
    complaints: 'शिकायतें',
    staffOnLeaveTag: 'स्टाफ अवकाश पर',
    totalComplaintsCount: 'कुल शिकायतें',
    noStaffOnLeave: 'कोई स्टाफ अवकाश पर नहीं',
    noComplaintsType: 'कोई शिकायत नहीं',
    complaintsWillAppear: 'शिकायतें यहाँ दिखाई देंगी',
    noStaffLeaveComplaints: 'कोई शिकायत स्टाफ अवकाश से संबंधित नहीं है',
    complaintsStatusAppear: 'इस स्थिति की शिकायतें यहाँ दिखाई देंगी',

    // 6. Asset Details Screen
    equipmentId: 'उपकरण आईडी:',
    type: 'प्रकार:',
    locationRequired: 'स्थान आवश्यक है',
    editLocation: 'स्थान *',
    editBrand: 'ब्रांड',
    editModel: 'मॉडल',
    installedDate: 'स्थापना तिथि',
    updateSuccess: 'उपकरण विवरण अपडेट हो गया',
    updateFailed: 'उपकरण अपडेट करने में विफल',
    activate: 'सक्रिय करें',
    deactivate: 'निष्क्रिय करें',
    activateEquipment: 'उपकरण सक्रिय करें?',
    deactivateEquipment: 'उपकरण निष्क्रिय करें?',
    activateMessage: 'यह उपकरण को फिर से सक्रिय कर देगा।',
    deactivateMessage: 'यह उपकरण को निष्क्रिय कर देगा। यह QR स्कैन में नहीं दिखेगा।',
    toggleFailed: 'स्थिति बदलने में विफल',
    availableForComplaints: 'शिकायतों के लिए उपलब्ध',
    hiddenFromQR: 'QR स्कैन से छिपा हुआ',
    qrCode: 'क्यूआर कोड',
    scanHint: 'समस्या रिपोर्ट करने के लिए Scan2Fix ऐप से इस QR को स्कैन करें',
    getQrCode: 'QR कोड प्राप्त करें',
    qrSaved: 'QR कोड सफलतापूर्वक बन गया',
    qrFailed: 'QR कोड बनाने में विफल',
    selectDateTitle: 'तारीख चुनें',

    // 7. Complaint Details Screen
    complaintDetails: 'शिकायत विवरण',
    attachedPhoto: 'संलग्न फोटो',
    assignStaff: 'स्टाफ असाइन करें',
    assignedStaff: 'असाइन किया गया स्टाफ',
    describeIssue: 'समस्या का विवरण लिखें...',
    characters: 'अक्षर',
    minChars: '(कम से कम 10)',
    assign: 'स्टाफ असाइन करें',
    reassign: 'स्टाफ पुनः असाइन करें',
    selectStaffError: 'कृपया स्टाफ सदस्य चुनें',
    cannotAssign: 'असाइन नहीं कर सकते',
    staffOnLeaveMsg: 'अवकाश पर है',
    descriptionEmpty: 'विवरण खाली नहीं हो सकता',
    descriptionMin: 'विवरण कम से कम 10 अक्षरों का होना चाहिए',
    descUpdated: 'विवरण अपडेट हो गया',
    descUpdateFailed: 'विवरण अपडेट करने में विफल',
    selectStaff: 'स्टाफ सदस्य चुनें',
    selectedStaff:'चयनित स्टाफ',
    selectStaffPlaceholder: '-- स्टाफ चुनें --',
    available: '✓',
    current: 'वर्तमान:',
    maintenanceStaff: 'मेंटेनेंस स्टाफ',
    pendingAssignment: 'असाइनमेंट लंबित',
    staffWillAssign: 'जल्द ही स्टाफ सदस्य असाइन किया जाएगा',
    staffOnLeaveWarning: 'असाइन किया गया स्टाफ अवकाश पर है। पुनः असाइन करें।',
    staffCurrentlyOnLeave: 'यह स्टाफ सदस्य वर्तमान में अवकाश पर है',
    selectedStaffOnLeave: 'यह स्टाफ सदस्य अवकाश पर है',

    // 8. Manage Users Screen
    manageUsers: 'उपयोगकर्ता प्रबंधन',
    searchUsers: 'नाम, ईमेल या आईडी से खोजें...',
    filterUsers: 'उपयोगकर्ताओं को फ़िल्टर करें',
    allUsers: 'सभी उपयोगकर्ता',
    admins: 'एडमिन',
    allStaff: 'सभी स्टाफ',
    users: 'उपयोगकर्ता',
    byDesignation: 'पद के अनुसार',
    onDuty: 'ड्यूटी पर',
    onLeaveStatus: 'अवकाश पर',
    markOnLeaveTitle: 'अवकाश पर चिह्नित करें',
    markAvailableTitle: 'उपलब्ध चिह्नित करें',
    confirm: 'पुष्टि करें',
    markStatusMessage: 'उपयोगकर्ता की स्थिति बदलें?',
    userNowStatus: 'अब है',
    usersCount: 'उपयोगकर्ता',
    noUsersFound: 'कोई उपयोगकर्ता नहीं मिला',
    noStaffOnDuty: 'कोई स्टाफ ड्यूटी पर नहीं',
    noUsersRole: 'कोई उपयोगकर्ता नहीं',
    tryDifferentFilter: 'कोई अन्य फ़िल्टर आज़माएँ',

    // 9. User Details Screen
    userDetails: 'उपयोगकर्ता विवरण',
    joinedOn: 'जॉइन करने की तिथि:',
    enterPhone: 'फोन नंबर दर्ज करें',
    userUpdated: 'उपयोगकर्ता विवरण अपडेट हो गया',
    staffActions: 'स्टाफ क्रियाएँ',
    markAsAvailable: 'उपलब्ध करें',
    markAsOnLeave: 'अवकाश पर करें',
    currentlyOnLeave: 'वर्तमान में अवकाश पर',
    dangerZone: 'खतरे का क्षेत्र',
    deleteUser: 'उपयोगकर्ता हटाएं',
    deleteWarning: 'यह उपयोगकर्ता और उससे संबंधित सभी डेटा को स्थायी रूप से हटा देगा',
    deleteUserTitle: 'उपयोगकर्ता हटाएं?',
    deleteUserConfirm: 'क्या आप इस उपयोगकर्ता को हटाना चाहते हैं?',
    masterAdminProtected: 'मास्टर एडमिन खाता सुरक्षित है और हटाया नहीं जा सकता',
    fullNameRequired: 'पूरा नाम आवश्यक है',
    userUpdateFailed: 'उपयोगकर्ता अपडेट करने में विफल',

    // ── AUTH ──────────────────────────────────────────────────────────────────

    // 1. Forgot Password Screen
    forgotPassword: 'पासवर्ड भूल गए?',
    enterResetCode: 'रीसेट कोड दर्ज करें',
    newPasswordTitle: 'नया पासवर्ड',
    enterEmailSubtitle: 'अपना ईमेल दर्ज करें, हम रीसेट कोड भेजेंगे',
    enterCodeSubtitle: 'अपने एडमिन से प्राप्त 6 अंकों का कोड दर्ज करें',
    createPasswordSubtitle: 'एक मजबूत नया पासवर्ड बनाएं',
    emailPlaceholder: 'ईमेल पता',
    codePlaceholder: '000000',
    newPasswordPlaceholder: 'नया पासवर्ड',
    confirmPasswordPlaceholder: 'पासवर्ड की पुष्टि करें',
    sendResetCode: 'रीसेट कोड भेजें',
    resetPassword: 'पासवर्ड रीसेट करें',
    previousStep: 'पिछला चरण',
    backToLogin: 'लॉगिन पर वापस जाएं',
    codeSentForgot: 'रीसेट कोड जनरेट किया गया है',
    failedToSendCode: 'कोड भेजने में विफल',
    enterCodeError: 'कृपया 6 अंकों का कोड दर्ज करें',
    passwordTooShort: 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
    passwordRequirements: 'पासवर्ड में कम से कम एक अक्षर और एक संख्या होनी चाहिए',
    passwordReset: 'पासवर्ड रीसेट हो गया! ✅',
    passwordResetMsg: 'अब आप नए पासवर्ड से लॉगिन कर सकते हैं',
    failedToReset: 'पासवर्ड रीसेट करने में विफल',

    // 2. Login Screen
    welcomeBack: 'वापसी पर स्वागत है!',
    loginSubtitle: 'अपने Scan2Fix खाते में लॉगिन करें',
    passwordPlaceholder: 'पासवर्ड',
    login: 'लॉग इन करें',
    loggingIn: 'लॉग इन हो रहा है...',
    noAccount: 'खाता नहीं है?',
    enterPassword: 'कृपया अपना पासवर्ड दर्ज करें',
    loginFailed: 'लॉगिन विफल',
    orSignIn: 'या साइन इन करें',
    enterValidEmailExample: 'कृपया सही ईमेल दर्ज करें\n\nउदाहरण: user@company.com',

    // 3. Signup Screen
    createAccount: 'खाता बनाएं',
    joinScan2Fix: 'Scan2Fix से जुड़ें',
    fixIssues: 'समस्याओं को ठीक करें',
    reportIssues: 'समस्याओं की रिपोर्ट करें',
    selectRolePrompt: 'मैं इस रूप में जुड़ना चाहता/चाहती हूँ',
    reportIssuesDesc: 'समस्याएँ रिपोर्ट करें',
    fixIssuesDesc: 'समस्याएँ ठीक करें',
    selectYourRole: 'अपनी भूमिका चुनें',
    employeeIdSignup: 'कर्मचारी आईडी (जैसे: EMP001)',
    phonePlaceholder: 'फोन (10 अंक, वैकल्पिक)',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    profilePhoto: 'प्रोफ़ाइल फोटो',
    photoCancel: 'रद्द करें',
    resendIn: 'पुनः भेजें',
    enterVerificationCodePrompt: 'वेरिफिकेशन कोड दर्ज करें',
    checkEmailCode: 'अपने ईमेल में 6 अंकों का कोड देखें',
    emailExists: 'ईमेल पहले से पंजीकृत है',
    goToLogin: 'लॉगिन पर जाएं',
    invalidCode: 'अमान्य कोड',
    enterCode6: 'कृपया 6 अंकों का कोड दर्ज करें',
    verifyEmailFirst: 'पहले अपना ईमेल सत्यापित करें',
    passwordRequired: 'कृपया पासवर्ड दर्ज करें',
    invalidPhone: 'अमान्य फोन',
    phoneDigits: 'फोन नंबर 10 अंकों का होना चाहिए',
    phoneStart: 'भारतीय नंबर 6, 7, 8 या 9 से शुरू होना चाहिए',
    employeeIdRequiredSignup: 'स्टाफ के लिए कर्मचारी आईडी आवश्यक है',
    photoRequiredTitle: 'फोटो आवश्यक है',
    accountCreated: 'खाता बन गया! 🎉',
    signupFailed: 'साइनअप विफल',
    verificationRequired: 'सत्यापन आवश्यक',
    signUpBtn: 'साइन अप करें',
    creatingBtn: 'बनाया जा रहा है...',
    alreadyAccount: 'क्या आपका खाता है?',
    nameMin: 'नाम कम से कम 2 अक्षरों का होना चाहिए',

    // ── SHARED SCREENS ────────────────────────────────────────────────────────

    // Profile Screen
    loadingProfile: 'परिचय विवरण लोड हो रही है…',
    profileInformation: 'परिचय विवरण',
    profileInfo: 'परिचय विवरण',
    theme: 'थीम',
    language: 'भाषा',
    enterName: 'अपना नाम दर्ज करें',
    phonePlaceholderProfile: '10 अंकों का फोन नंबर दर्ज करें',
    validPhone: 'मान्य फोन नंबर',
    enterNameError: 'कृपया अपना नाम दर्ज करें',
    phoneMustBe10: 'फोन नंबर 10 अंकों का होना चाहिए',
    profileUpdated: 'परिचय विवरण सफलतापूर्वक अपडेट हुई',
    profileUpdateFailed: 'परिचय विवरण अपडेट करने में विफल',
    changePassword: 'पासवर्ड बदलें',
    currentPassword: 'वर्तमान पासवर्ड',
    newPassword: 'नया पासवर्ड (कम से कम 6 अक्षर)',
    confirmNewPassword: 'नए पासवर्ड की पुष्टि करें',
    updatePassword: 'पासवर्ड अपडेट करें',
    currentPasswordRequired: 'कृपया अपना वर्तमान पासवर्ड दर्ज करें',
    passwordChanged: 'पासवर्ड सफलतापूर्वक बदल गया',
    passwordChangeFailed: 'पासवर्ड बदलने में विफल',
    deleteAccount: 'खाता हटाएं',
    deleteAccountWarning: 'यह क्रिया स्थायी है और वापस नहीं की जा सकती। आपका सारा डेटा हट जाएगा।',
    enterPasswordToConfirm: 'पुष्टि के लिए पासवर्ड दर्ज करें',
    deleteAccountForever: 'मेरा खाता स्थायी रूप से हटाएं',
    finalConfirmation: '⚠️ अंतिम पुष्टि',
    deleteConfirmMsg: 'क्या आप सुनिश्चित हैं? यह क्रिया वापस नहीं की जा सकती।\n\nआपका खाता और संबंधित डेटा स्थायी रूप से हट जाएगा।',
    accountDeleted: 'खाता हटाया गया',
    accountDeletedMsg: 'आपका खाता स्थायी रूप से हटाया गया है',
    deleteFailed: 'खाता हटाने में विफल',
    logout: 'लॉग आउट',
    logoutConfirm: 'क्या आप लॉग आउट करना चाहते हैं?',
    appName: 'Scan2Fix',
    version: 'संस्करण',

    // ── STAFF ─────────────────────────────────────────────────────────────────

    // 1. Job Details Screen
    jobDetails: 'जॉब विवरण',
    photoOfIssue: 'समस्या की फोटो',
    actions: 'क्रियाएँ',
    startWorking: 'काम शुरू करें',
    finishWorking: 'काम पूरा करें',
    enterOtpToComplete: 'पूरा करने के लिए OTP दर्ज करें',
    verifyAndClose: 'सत्यापित करें और बंद करें',
    statusUpdated: 'स्थिति अपडेट हुई:',
    otpIncomplete: 'कृपया पूरा 6 अंकों का OTP दर्ज करें',
    finishHint: 'काम पूरा होने पर क्लिक करें।',
    otpHint: 'जॉब बंद करने के लिए उपयोगकर्ता से OTP लें',
    otpNote: 'यह OTP उपयोगकर्ता अपने ऐप से जनरेट करता है',
    enterCompletionOtp: 'पूर्णता OTP दर्ज करें',
    otpSubtitle: 'सत्यापन के लिए उपयोगकर्ता से 6 अंकों का OTP लें',

    // 2. Staff Dashboard Screen
    goOnLeaveTitle: '🏖️ अवकाश पर जाएं?',
    comeBackTitle: 'वापस आएं?',
    goOnLeaveMsg: 'अवकाश के दौरान आपको नए कार्य असाइन नहीं किए जाएंगे।\n\nआपके वर्तमान कार्य तब तक असाइन रहेंगे जब तक एडमिन उन्हें बदल न दे।',
    comeBackMsg: 'अब आपको फिर से नए कार्य असाइन होने लगेंगे।',
    goOnLeave: 'अवकाश पर जाएं',
    comeBack: 'वापस आएं',
    yesGoOnLeave: 'हाँ, अवकाश पर जाएं',
    yesAvailable: 'हाँ, मैं उपलब्ध हूँ',
    available: 'उपलब्ध',
    notReceivingTasks: 'नए कार्य नहीं मिल रहे',
    receivingTasks: 'कार्य असाइन हो रहे हैं',
    onLeaveSuccess: '🏖️ अवकाश पर',
    job: 'जॉब',
    jobs: 'जॉब्स',
    viewDetails: 'विवरण देखें',
    hasPhoto: 'फोटो संलग्न है',
    noNewTasks: 'कोई नया कार्य नहीं',
    noTasksInProgress: 'कोई कार्य प्रगति में नहीं',
    noCompletedTasks: 'कोई पूर्ण कार्य नहीं',
    newTasksHint: 'नए कार्य यहाँ दिखाई देंगे',
    inProgressHint: 'जो कार्य आप कर रहे हैं वे यहाँ दिखेंगे',
    completedHint: 'पूर्ण कार्य यहाँ दिखाई देंगे',

    // ── USER ──────────────────────────────────────────────────────────────────

    // 1. Lodge Complaint Screen
    lodgeComplaint: 'शिकायत दर्ज करें',
    issuePlaceholder: 'समस्या क्या है? कृपया विस्तार से बताएं...',
    describeIssueLabel: 'समस्या का विवरण',
    attachPhoto: 'फोटो जोड़ें (वैकल्पिक)',
    camera: 'कैमरा',
    takePhotoLabel: 'फोटो लें',
    gallery: 'गैलरी',
    chooseExisting: 'मौजूदा फोटो चुनें',
    photoAttached: 'फोटो जुड़ी हुई है',
    permissionNeeded: 'अनुमति आवश्यक',
    cameraPermission: 'कैमरा की अनुमति आवश्यक है',
    galleryPermission: 'गैलरी की अनुमति आवश्यक है',
    describeIssueError: 'कृपया समस्या का विवरण दें',
    complaintSubmitted: 'शिकायत सफलतापूर्वक दर्ज हो गई',
    submitComplaint: 'शिकायत सबमिट करें',
    submitting: 'सबमिट हो रहा है...',
    uploadingPhoto: 'फोटो अपलोड हो रही है...',

    // 2. My Complaints Screen
    myComplaints: 'मेरी शिकायतें',
    finishing: 'पूरा हो रहा है',
    totalComplaintsLabel: 'कुल शिकायतें —',
    tapToViewImage: 'पूरी तस्वीर देखने के लिए टैप करें',
    generateOtp: 'पूरा करने के लिए OTP जनरेट करें',
    shareOtp: 'OTP साझा करें',
    completionOtp: 'पूर्णता OTP',
    otpSubtitleUser: 'सत्यापन के लिए यह OTP तकनीशियन को दें',
    validFor: '5 मिनट तक मान्य',
    otpNoteUser: 'तकनीशियन इस OTP को अपने ऐप में डालकर समस्या को बंद करेगा',
    generateOtpFailed: 'OTP जनरेट करने में विफल',
    noComplaintsDesc: 'आपकी शिकायतें यहाँ दिखाई देंगी',
    noFilteredComplaints: 'कोई शिकायत नहीं मिली',
    noFilteredDesc: 'इस स्थिति की शिकायतें यहाँ दिखाई देंगी',
    calendar: 'कैलेंडर',

    // 3. Scan QR Screen
    requestingPermission: 'कैमरा अनुमति मांगी जा रही है...',
    cameraAccessNeeded: 'कैमरा एक्सेस आवश्यक है',
    cameraPermissionDesc: 'मशीन के QR कोड स्कैन करने के लिए कैमरा अनुमति आवश्यक है',
    grantPermission: 'अनुमति दें',
    enterManuallyLink: 'या एसेट आईडी मैन्युअली दर्ज करें',
    scanQrCode: 'QR कोड स्कैन करें',
    scanInstructions: 'कैमरा को मशीन के QR कोड पर रखें',
    enterIdManually: 'आईडी मैन्युअली दर्ज करें',
    scanAgain: 'फिर से स्कैन करने के लिए टैप करें',
    lookingUpAsset: 'एसेट खोजा जा रहा है...',
    assetNotFound: 'एसेट नहीं मिला ❌',
    assetNotFoundMsg: 'इस आईडी के साथ कोई मशीन नहीं मिली:',
    invalidQrHint: 'कृपया सही Scan2Fix QR कोड स्कैन करें',
    tryAgain: 'फिर से प्रयास करें',
    enterManually: 'मैन्युअली दर्ज करें',
    scanFailed: 'QR कोड प्रोसेस करने में विफल। कृपया पुनः प्रयास करें।',
    enterAssetId: 'एसेट आईडी दर्ज करें',
    enterAssetHint: 'मशीन पर लिखी आईडी दर्ज करें (जैसे: AC-101, WC-201)',
    assetPlaceholder: 'जैसे: AC-101',
    submit: 'सबमिट करें',
    enterAssetError: 'कृपया एसेट आईडी दर्ज करें',

    // 4. User Dashboard Screen
    scanQR: 'QR कोड स्कैन करें',
    reportIssue: 'समस्या रिपोर्ट करें',
    howItWorks: 'यह कैसे काम करता है:',
    step1: 'मशीन पर QR कोड स्कैन करें',
    step2: 'समस्या का विवरण दें',
    step3: 'फोटो लें (वैकल्पिक)',
    step4: 'सबमिट करें और स्थिति ट्रैक करें',

    // 5. Verify OTP Screen
    verifyComplaint: 'शिकायत सत्यापित करें',
    verifyCompletion: 'पूर्णता सत्यापित करें',
    otpInstruction: 'मेंटेनेंस स्टाफ द्वारा दिया गया 6 अंकों का OTP दर्ज करें',
    enterOtp: 'OTP दर्ज करें',
    otpExpired: 'OTP समाप्त हो गया',
    timeRemaining: 'शेष समय',
    verifyAndCloseComplaint: 'सत्यापित करें और शिकायत बंद करें',
    invalidOtpMsg: 'कृपया सही 6 अंकों का OTP दर्ज करें',
    verificationFailed: 'सत्यापन विफल',
    verified: 'सत्यापित! ✅',
    otpExpiredMsg: 'OTP समाप्त हो गया है। कृपया स्टाफ से नया OTP प्राप्त करें।',
    otpHelpNote: 'मेंटेनेंस स्टाफ काम पूरा करने के बाद यह OTP देगा। OTP 5 मिनट तक मान्य है।',
  },
};

// MERGED TRANSLATIONS  (shared keys first, screen-specific keys override if needed)
const TRANSLATIONS = {
  en: { ...SHARED.en, ...SCREEN_TRANSLATIONS.en },
  hi: { ...SHARED.hi, ...SCREEN_TRANSLATIONS.hi },
};

// PROVIDER
export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState('en');
  const [isFirstLaunch, setIsFirstLaunch] = useState(false);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const saved = await SecureStore.getItemAsync('appLanguage');
      if (saved) {
        setLanguageState(saved);
      } else {
        setIsFirstLaunch(true);
      }
    } catch (e) {}
    setLoaded(true);
  };

  const setLanguage = async (lang) => {
    setLanguageState(lang);
    setIsFirstLaunch(false);
    await SecureStore.setItemAsync('appLanguage', lang);
  };

  // Falls back to English, then to the raw key
  const t = (key) =>
    TRANSLATIONS[language]?.[key] ?? TRANSLATIONS['en']?.[key] ?? key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isFirstLaunch, loaded }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);